<tr>
    <td colspan="2" class="fieldset-row">
        <fieldset id="<?php echo $this->get('formElement')->getAttribute('id'); ?>">
        <table
            class="tbl-fieldset <?php echo $this->get('formElement')->getAttribute('class');?>"
            id="tbl-<?php echo $this->get('formElement')->getName(); ?>"
            >
        <?php
        /** @var \Zend\Form\Fieldset $element */
        $element = $this->get('formElement');
        IF($element->getLabel()) :
        ?>
            <thead>
                <tr>
                    <th colspan="2"><?php echo $this->formLabel($element); ?></th>
                </tr>
            </thead>
        <?php
        ENDIF;
        ?>
        <tbody>
        <?php
            echo $this->get('content');
        ?>
        </tbody>
        </table>
        </fieldset>
    </td>
</tr>

