<?php
/**
 * Created by PhpStorm.
 * User: kota
 * Date: 29.01.17
 * Time: 23:32
 */
use Zend\Json\Json;

$content = $this->get('content');
/** @var Zend\Form\Form $formElement */
$formElement = $this->get('formElement');

$gridName = 'Grid'.$formElement->getName();
$opts = $formElement->getOption('jqGrid');
if (array_key_exists('pager', $opts) && $opts['pager'] == true) {
    $pagerId = 'GridPager-'.$gridName;
} else {
    $pagerId = 'undefined';
}

?>
<table id="<?php echo $gridName; ?>"></table>
<script>
    $(document).ready(function() {
        var gridSelector = '#<?php echo $gridName;?>';
        var pagerSelector = undefined;
        var gridPagerId = '<?php echo $pagerId; ?>';
        if (gridPagerId != undefined) {
            jQuery('#<?php echo $gridName; ?>').after("<div id=\'" + gridPagerId + "\'></div>");
            pagerSelector = '#'.gridPagerId;
        }

        <?php
        echo $this->get('content');
        ?>

    });
</script>
