<?php
/**
 * Created by PhpStorm.
 * User: kota
 * Date: 31.01.17
 * Time: 23:23
 */
/** @var \Zend\Form\Form $form */
$form = $this->get('formElement');
$gridName = 'Grid'.$form->getName();
$opts = $formElement->getOption('jqGrid');
if (array_key_exists('pager', $opts) && $opts['pager'] == true) {
    $pagerId = 'GridPager-'.$gridName;
} else {
    $pagerId = 'undefined';
}
?>
<table id="<?php echo $gridName;?>"></table>
<script>
$(document).ready(function() {
    var gridSelector = '#<?php echo $gridName;?>';
    var pagerSelector = undefined;
    var gridPagerId = '<?php echo $pagerId; ?>';
    if (gridPagerId != undefined) {
        jQuery('#<?php echo $gridName; ?>').after("<div id=\'" + gridPagerId + "\'></div>");
        pagerSelector = '#'.gridPagerId;
    }

    var gridFunction = <?php echo $this->get('content'); ?>;

    var gridObj = gridFunction(gridSelector, pagerSelector);
});
</script>