<?php
/**
 * Created by PhpStorm.
 * User: kota
 * Date: 31.01.17
 * Time: 23:23
 */
/** @var \Zend\Form\Form $form */
$form = $this->get('formElement');
$gridName = 'Grid'.$form->getName();
$opts = $form->getOption('jqGrid');
if (array_key_exists('pager', $opts) && $opts['pager'] == true) {
    $pagerId = 'GridPager-'.$gridName;
} else {
    $pagerId = 'undefined';
}

?>
<table id="<?php echo $gridName;?>"></table>
<script>
$(document).ready(function() {
    var gridSelector = '#<?php echo $gridName;?>';
    var pagerSelector = undefined;
    var gridPagerId = '<?php echo $pagerId; ?>';
    if (gridPagerId != undefined) {
        jQuery('#<?php echo $gridName; ?>').after("<div id=\'" + gridPagerId + "\'></div>");
        pagerSelector = '#'+gridPagerId;
    }

    var gridFunction = <?php echo $this->get('content'); ?>;

    var gridObj = gridFunction(gridSelector, pagerSelector);

    <?php
     $gridMethods = $form->getOption('jqGridMethods');
     if (is_array($gridMethods)) {
         foreach ($gridMethods as $methodObj) {
            echo 'gridObj.jqGrid('. $methodObj . ");\n";
         }
     }
    ?>

//    gridObj.jqGrid('navButtonAdd',pagerSelector, {
//        caption: "Columns",
//        title: "Reorder Columns",
//        onClickButton : function (){
//            gridObj.jqGrid('columnChooser');
//        }
//    });

//    gridObj.jqGrid('setGroupHeaders', {
//      useColSpanStyle: true,
//      groupHeaders:[
//        {startColumnName: 'name', numberOfColumns: 2, titleText: '<em>Объединяем 1-2</em>'}
//        //{startColumnName: 'closed', numberOfColumns: 2, titleText: 'Shiping'}
//      ]
//    });

//    gridObj.jqGrid('hideCol', 'status'); //спрятать колонку
//    gridObj.jqGrid('showCol', 'status');
});
</script>