<?php
/**
 * Created by PhpStorm.
 * User: kota
 * Date: 28.01.17
 * Time: 15:50
 */
use \Zend\Form\Element\Collection;

$options = $this->get('options');
if (array_key_exists('branch', $options)) {
    $branch = $options['branch'];
} else {
    $branch = $this->get('branch');
}
$mode = $this->get('mode');
/** @var Collection $collection */
$collection = $this->get('formElement');
if ($collection->shouldCreateTemplate()) {
    if ($template = $collection->getTemplateElement()) {
        $templateMarkup = $this->formBranchRender($template, $branch, $mode);
    }
}
/** @var \Zend\Form\Element $element */
foreach ($collection as $element) {
    if ($element->getLabel()) {
        echo  $this->form_label($element);
    }
    echo $this->formBranchRender($element, $branch, $mode);
}
