<?php
/**
 * Created by PhpStorm.
 * User: kota
 * Date: 23.01.17
 * Time: 22:53
 */
$options = $this->get('options');
if (array_key_exists('branch', $options)) {
    $branch = $options['branch'];
} else {
    $branch = $this->get('branch');
}
$mode = $this->get('mode');
/** @var \Zend\Form\Element $element */
$element = $this->get('formElement');
$id = $element->getAttribute('id');
$element->setAttribute('data-type', $element->getAttribute('type'));
if (($currentMode = $element->getOption('mode')) == null) {
    $currentMode = $mode;
}

$errorMsg = $errClass = '';
if (isset($options['markupError'])) {
    $errorMsg = $options['markupError'];
    $element->setAttribute('class', $element->getAttribute('class') . ' input-error-element');
}

//echo '<div class="element-wrapper">';
printf('<div class="element-wrapper element-wrapper-type-%s element-wrapper-id-%s">',
    $element->getAttribute('type'), $id
);
if ($currentMode == 'view') {
    $value = $element->getValue();
    printf('<span id="info-%s" class="info-%s %s">%s</span>',
        $id, $id,
        $element->getAttribute('class'),
        $value
    );
    echo $errorMsg;
    echo $this->formHidden($element);
} else {
    echo $this->formText($element);
    echo $errorMsg;
}
echo '</div>';
