<?php
/**
 * Created by PhpStorm.
 * User: kota
 * Date: 23.01.17
 * Time: 22:53
 */
$options = $this->get('options');
if (array_key_exists('branch', $options)) {
    $branch = $options['branch'];
} else {
    $branch = $this->get('branch');
}
$mode = $this->get('mode');
/** @var \Zend\Form\Element $element */
$element = $this->get('formElement');
if ($mode == 'view') {
    $value = $element->getValue();
    echo '<span>'. $value .'</span>';
    echo $this->formHidden($element);
} else {
    echo $this->formDate($element);
}
