<?php
/**
 * Created by PhpStorm.
 * User: kota
 * Date: 22.01.17
 * Time: 23:14
 */
use \Zend\Form\FieldsetInterface;

/** @var \Zend\Form\Fieldset $fieldset */
$fieldset = $this->get('formElement');
/** @var \Zend\Form\Element $element */
foreach ($fieldset as $element) {
    $content .= $this->formElementView($element, $this->get('branch'), '', [
        'template' => '/FormElementDecorators/table/table-row'
    ]);
}
echo $content;

