<?php
/**
 * Created by PhpStorm.
 * User: kota
 * Date: 22.01.17
 * Time: 23:14
 */
use \Zend\Form\FieldsetInterface;

/** @var \Zend\Form\Fieldset $fieldset */
$fieldset = $this->get('formElement');
$content = '<fieldset><table>';
$content .= '<label>' . $fieldset->getLabel() . '</label>';
/** @var \Zend\Form\Element $element */
foreach ($fieldset as $element) {
    $content .= '<tr>'
        . '<td>'.$element->getLabel() . '</td>'
        . '<td>' . $this->formDecorator($element, $this->get('branch')) . '</td>'
    .'</tr>';
}
$content .= '</table></fieldset>';
echo $content;

