<?php
/**
 * Created by PhpStorm.
 * User: kota
 * Date: 22.01.17
 * Time: 23:14
 */
use \Zend\Form\FieldsetInterface;

$options = $this->get('options');
if (array_key_exists('branch', $options)) {
    $branch = $options['branch'];
} else {
    $branch = $this->get('branch');
}
$mode = $this->get('mode');
/** @var \Zend\Form\Fieldset $fieldset */
$fieldset = $this->get('formElement');

echo "<fieldset>\n";
if (($label = $fieldset->getLabel()) != null) {
    echo '<label>'.$label."</label>\n";
}
echo $this->get('content');
echo "</fieldset>\n";

