<?php
/**
 * Created by PhpStorm.
 * User: kota
 * Date: 23.01.17
 * Time: 22:53
 */

$options = $this->get('options');
if (array_key_exists('branch', $options)) {
    $branch = $options['branch'];
} else {
    $branch = $this->get('branch');
}
$mode = $this->get('mode');
/** @var \Zend\Form\Element $element */
$element = $this->get('formElement');
$id = $element->getAttribute('id');
if (($currentMode = $element->getOption('mode')) == null) {
    $currentMode = $mode;
}
$errorMsg = $errClass = '';
if (isset($options['markupError'])) {
    $errorMsg = $options['markupError'];
    $element->setAttribute('class', $element->getAttribute('class') . ' input-error-element');
}
if (($value = $element->getValue()) != null) {
    $element->setAttribute('src', $value);
}

$elementOptions = $element->getOptions();
$elementOptions['wrapperAttributes']['class'] = sprintf("element-wrapper element-wrapper-type-%s element-wrapper-id-%s %s",
    $element->getAttribute('type'),
    $id,
    (isset($elementOptions['wrapperAttributes']['class']) ? $elementOptions['wrapperAttributes']['class'] : '')
);
$ctrlWrapAtt = [];
foreach($elementOptions['wrapperAttributes'] as $k => &$v) {
    $ctrlWrapAtt[] = "$k='$v'";
}

echo '<div '. implode(' ', $ctrlWrapAtt) .'>';

if ($currentMode == 'view') {
    echo '<img ';
    foreach($element->getAttributes() as $k=>&$v) {
        printf(' %s="%s"', $k, $v);
    }
    echo '>';
    echo $errorMsg;
} else {
    echo $this->formImage($element);
    echo $errorMsg;
}
echo '</div>';