<?php
$options = $this->get('options');
if (array_key_exists('branch', $options)) {
    $branch = $options['branch'];
} else {
    $branch = $this->get('branch');
}
$mode = $this->get('mode');
/** @var \Zend\Form\Fieldset $fieldset */
$fieldset = $this->get('formElement');
$id = $fieldset->getAttribute('id');

$fieldsetOptions = $fieldset->getOptions();
if (!isset($fieldsetOptions['wrapperAttributes']['class'])) {
    $fieldsetOptions['wrapperAttributes']['class'] = '';
}
$fieldsetOptions['wrapperAttributes']['class'] = sprintf('element-wrapper element-wrapper-type-%s element-wrapper-id-%s %s',
    $fieldset->getAttribute('type'),
    $id,
    $fieldsetOptions['wrapperAttributes']['class']
);

$ctrlWrapAtt = [];
foreach($fieldsetOptions['wrapperAttributes'] as $k => &$v) {
    $ctrlWrapAtt[] = "$k='$v'";
}

echo '<div '. implode(' ', $ctrlWrapAtt) .'>';

/** @var \Zend\Form\Element $element */
foreach ($fieldset as $element) {
    if ($element instanceof \Zend\Form\Element\Button ==false) {
        if ($element->getLabel()) {
            echo $this->formLabel($element);
        }
    }
    echo $this->formBranchRender($element, $branch, $mode) . "\n";
}

echo '</div>';


