<?php
/**
 * Created by PhpStorm.
 * User: kota
 * Date: 23.01.17
 * Time: 22:53
 */
$options = $this->get('options');
if (array_key_exists('branch', $options)) {
    $branch = $options['branch'];
} else {
    $branch = $this->get('branch');
}
$mode = $this->get('mode');
/** @var \Zend\Form\Element\Radio $element */
$element = $this->get('formElement');
$id = $element->getAttribute('id');
if ($mode == 'view') {
    $valueOptions = $element->getValueOptions();
    $key = $element->getValue();
    $value = null;
    foreach ($valueOptions as $k => &$v) {
        if (is_array($v)) {
            //TODO есть такой расширенный формат опций
        } else {
            if ($k == $key) {
                $value = $v;
                break;
            }
        }
    }
    printf('<span id="info-%s" class="info-%s %s">%s</span>',
        $id, $id,
        $element->getAttribute('class'),
        $value
    );
    echo $this->formHidden($element);
} else {
    echo $this->formRadio($element);
}


