<?php
/**
 * Created by PhpStorm.
 * User: kota
 * Date: 23.01.17
 * Time: 22:53
 */
$options = $this->get('options');
if (array_key_exists('branch', $options)) {
    $branch = $options['branch'];
} else {
    $branch = $this->get('branch');
}
$mode = $this->get('mode');
/** @var \Zend\Form\Element\Select $element */
$element = $this->get('formElement');
if ($mode == 'view') {
    $key = $element->getValue();
    $value = null;
    if (method_exists($element, 'findOne')) {
        $value = $element->findOne($key);
    } else {
        $valueOptions = $element->getValueOptions();
        foreach ($valueOptions as $k => &$v) {
            if (is_array($v)) {
                //TODO есть такой расширенный формат опций
                if ($v['value'] == $key) {
                    $value = $v['label'];
                    break;
                }
            } else {
                if ($k == $key) {
                    $value = $v;
                    break;
                }
            }
        }
    }
    echo '<span>'.$value.'</span>';
    echo $this->formHidden($element);
} else {
    echo $this->formSelect($element);
}