<?php
/**
 * Created by PhpStorm.
 * User: kota
 * Date: 23.01.17
 * Time: 22:53
 */
$options = $this->get('options');
if (array_key_exists('branch', $options)) {
    $branch = $options['branch'];
} else {
    $branch = $this->get('branch');
}
$mode = $this->get('mode');
/** @var \Zend\Form\Element $element */
$element = $this->get('formElement');
$id = $element->getAttribute('id');
if (($currentMode = $element->getOption('mode')) == null) {
    $currentMode = $mode;
}
$errorMsg = $errClass = '';
if (isset($options['markupError'])) {
    $errorMsg = $options['markupError'];
    $element->setAttribute('class', $element->getAttribute('class') . ' input-error-element');
}

$elementOptions = $element->getOptions();
$elementOptions['wrapperAttributes']['class'] = sprintf("element-wrapper element-wrapper-type-%s element-wrapper-id-%s %s",
    $element->getAttribute('type'),
    $id,
    (isset($elementOptions['wrapperAttributes']['class']) ? $elementOptions['wrapperAttributes']['class'] : '')
);
$ctrlWrapAtt = [];
foreach($elementOptions['wrapperAttributes'] as $k => &$v) {
    $ctrlWrapAtt[] = "$k='$v'";
}

echo '<div '. implode(' ', $ctrlWrapAtt) .'>';
//printf('<div class="element-wrapper element-wrapper-type-%s element-wrapper-id-%s">',
//    $element->getAttribute('type'), $id
//);
if ($currentMode == 'view') {
    $value = $element->getValue();
    printf('<span id="info-%s" class="info-%s %s">%s</span>',
        $id, $id,
        $element->getAttribute('class'),
        $value
    );
    echo $errorMsg;
    echo $this->formHidden($element);
} else {
    echo $this->formText($element);
    echo $errorMsg;
}
echo '</div>';