<?php
use Zend\Form\Element;
/** @var \Zend\Form\Element $element */
$element = $this->get('formElement');

$labelAttributes = $element->getLabelAttributes();
$labelElement = new \Zend\Form\Element();
if (!isset($labelAttributes['class'])) {
    $labelAttributes['class'] = 'control-label col-sm-3 ';
    //$element->setLabelAttributes($labelAttributes);
}
$labelElement->setLabelAttributes($labelAttributes)
    ->setLabel($element->getLabel())
    ->setAttributes($element->getAttributes());
;

if(($classAtt = $element->getAttribute('class')) == null) {
    $classAtt = 'form-control ' . $classAtt;
    $element->setAttribute('class', $classAtt);
}

$options = $this->get('options');
$branch = 'default';
if (isset($options['branch']) == true) {
    $branch = $options['branch'];
}

$elementOptions = $element->getOptions();
if (!isset($elementOptions['wrapperAttributes']['class'])) {
    $elementOptions['wrapperAttributes']['class'] = 'col-sm-9';
}
$elementOptions['wrapperAttributes']['class'] = 'wrap-element-body ' . $elementOptions['wrapperAttributes']['class'];
$ctrlWrapAtt = [];
foreach($elementOptions['wrapperAttributes'] as $k => &$v) {
    $ctrlWrapAtt[] = "$k='$v'";
}

$label = ($element->getLabel()) ? $this->formLabel($element) : '';
$markup = $this->formBranchRender($element, $branch, $this->get('mode'));
$type = $element->getAttribute('type');
?>
<div class="form-group wrap-element-row wrap-element-row-<?php echo $type; ?>">
    <?= ($labelElement->getLabel() ? $this->formLabel($labelElement) : '') ?>
    <div <?= implode(' ', $ctrlWrapAtt); ?> ><?php echo $markup; ?></div>
</div>

