<?php
/** @var \Zend\Form\Element $element */
$element = $this->get('formElement');

$labelAttributes = $element->getLabelAttributes();
if (!isset($labelAttributes['class'])) {
    $labelAttributes['class'] = 'control-label col-sm-4 ';
    $element->setLabelAttributes($labelAttributes);
}

if(($classAtt = $element->getAttribute('class')) == null) {
    $classAtt = 'form-control ' . $classAtt;
    $element->setAttribute('class', $classAtt);
}

$options = $this->get('options');
$branch = 'default';
if (isset($options['branch']) == true) {
    $branch = $options['branch'];
}

if (!isset($options['ctrl_wrap_att']['class'])) {
    $options['ctrl_wrap_att']['class'] = 'col-sm-8';
}
$options['ctrl_wrap_att']['class'] = 'wrap-element-body ' . $options['ctrl_wrap_att']['class'];
$ctrlWrapAtt = [];
foreach($options['ctrl_wrap_att'] as $k => &$v) {
    $ctrlWrapAtt[] = "$k='$v'";
}

$label = ($element->getLabel()) ? $this->formLabel($element) : '';
$markup = $this->formBranchRender($element, $branch, $this->get('mode'));
$type = $element->getAttribute('type');
?>
<div class="form-group wrap-element-row wrap-element-row-<?php echo $type; ?>">
    <?php echo $label; ?>
    <div <?= implode(' ', $ctrlWrapAtt); ?> ><?php echo $markup; ?></div>
</div>

