<?php
use Zend\Form\Element;
/** @var \Zend\Form\Element $element */
$element = $this->get('formElement');
$options = $this->get('options');
$defaultLabelClass = array_key_exists('label_class', $options) ? $options['label_class'] : 'control-label col-sm-4 ';
$defaultBodyClass = array_key_exists('body_class', $options) ? $options['body_class'] : 'col-sm-8';

$labelAttributes = $element->getLabelAttributes();
$labelElement = new \Zend\Form\Element();
if (!isset($labelAttributes['class'])) {
    $labelAttributes['class'] = $defaultLabelClass;
}
$labelElement->setLabelAttributes($labelAttributes)
    ->setLabel($element->getLabel())
    ->setAttributes($element->getAttributes());
;


$branch = 'default';
if (isset($options['branch']) == true) {
    $branch = $options['branch'];
}

$elementOptions = $element->getOptions();
if (!isset($elementOptions['bodyAttributes']['class'])) {
    $elementOptions['bodyAttributes']['class'] = $defaultBodyClass;
}
$elementOptions['bodyAttributes']['class'] = 'wrap-element-body ' . $elementOptions['bodyAttributes']['class'];
$ctrlWrapAtt = [];
foreach($elementOptions['bodyAttributes'] as $k => &$v) {
    $ctrlWrapAtt[] = "$k='$v'";
}

//инлаин верстка радиобатонов
$labelAttributes = $element->getLabelAttributes();
if (isset($labelAttributes['class'])) {
    $labelAttributes['class'] .= ' radio-inline';
} else {
    $labelAttributes['class'] = 'radio-inline';
}
$element->setLabelAttributes($labelAttributes);

$markup = $this->formBranchRender($element, $branch, $this->get('mode'));
$type = $element->getAttribute('type');


?>
<div class="form-group wrap-element-row wrap-element-row-<?php echo $type; ?>">
    <?= ($labelElement->getLabel() ? $this->formLabel($labelElement) : '') ?>
    <div <?= implode(' ', $ctrlWrapAtt); ?> ><?php echo $markup; ?></div>
</div>

