<?php
/** @var \Zend\Form\Element\Collection $collection */
$collection = $this->get('formElement');
$target = $collection->getTargetElement();
?>
<thead>
    <tr>
        <?php
        /** @var \Zend\Form\Element $element */
        foreach($target as $element) {
            if ($element instanceof \Zend\Form\Element\Hidden) {
                continue;
            }
            ?>
            <th class="collection-txt"><?php echo ($element->getLabel()) ? $this->formLabel($element) : ''; ?></th>
        <?php
        }
        ?>
    </tr>
</thead>

