<tr>
    <td colspan="2" style="padding:2px;">
        <fieldset>
        <table class="tbl-fieldset" id="tbl-<?php echo $this->get('formElement')->getName(); ?>">
        <?php
        /** @var \Zend\Form\Fieldset $element */
        $element = $this->get('formElement');
        IF($element->getLabel()) :
        ?>
            <thead>
                <tr>
                    <th colspan="2"><?php echo $this->formLabel($element); ?></th>
                </tr>
            </thead>
        <?php
        ENDIF;
        ?>
        <tbody>
        <?php
            echo $this->get('content');
        ?>
        </tbody>
        </table>
        </fieldset>
    </td>
</tr>

