<?php
/**
 * Created by PhpStorm.
 * User: kota
 * Date: 22.01.17
 * Time: 23:14
 */
use \Zend\Form\FieldsetInterface;

$form = $this->get('formElement');
echo $this->form()->openTag($form);
$content = '';
foreach ($form as $element) {
    $content.= $this->formBranchRender($element, $this->get('branch'), $this->get('mode'));
}
echo $content;
echo '<p>branch => ' . $this->get('branch');
echo '<p>content => ' . $this->vars('content');

echo $this->form()->closeTag();
