<?php
/**
 * Created by PhpStorm.
 * User: kota
 * Date: 13.02.17
 * Time: 23:38
 */
use \Zend\Form\FieldsetInterface;
/** @var \Zend\Form\Form $form */
$form = $this->get('formElement');
$content = $this->get('content');
$baseFieldset = $form->getBaseFieldset();
$label = $baseFieldset->getLabel();
$errorMessage = $baseFieldset->getAttribute('error-message');
?>
<div class="panel panel-default form-panel">
    <div class="panel-heading">
        <?php echo $label; ?>
    </div>
    <div class="panel-body">
        <?php if($errorMessage): ?>
        <div class="text-danger form-panel-error"><?php echo $errorMessage; ?></div>
        <?php endif; ?>
        <?php echo $content; ?>
    </div>
</div>