<?php
/**
 * Created by PhpStorm.
 * User: kota
 * Date: 13.02.17
 * Time: 23:38
 */
use \Zend\Form\FieldsetInterface;
/** @var \Zend\Form\Form $form */
$form = $this->get('formElement');
$content = $this->get('content');
$baseFieldset = $form->getBaseFieldset();
$label = $baseFieldset->getLabel();
$errorMessage = $baseFieldset->getAttribute('error-message');

$classAtt = 'form-horizontal ' . $form->getAttribute('class');
$form->setAttribute('class', $classAtt);
echo $this->form()->openTag($form);
?>
<div class="panel panel-default wrap-form">
    <?php
    if ($label) {
        echo "<div class='panel-heading'>" . $this->formLabel($baseFieldset) . "</div>";
    }
    ?>
    <div class="panel-body">

        <div class="form-group">
            <?php if($errorMessage): ?>
            <div class="text-danger form-panel-error"><?php echo $errorMessage; ?></div>
            <?php endif; ?>
            <?php echo $content; ?>
        </div>
    </div>
<?php
echo $this->form()->closeTag();