<?php
/**
 * Created by PhpStorm.
 * User: kota
 * Date: 13.02.17
 * Time: 23:38
 */
use \Zend\Form\FieldsetInterface;

/** @var \Zend\Form\Element $element */
$element = $this->get('formElement');
$content = $this->get('content');
$label = $element->getLabel();
$errorMessage = $element->getAttribute('error-message');
?>
<div class="panel panel-default">
    <div class="panel-heading">
        <?php echo $label; ?>
    </div>
    <div class="panel-body">
        <?php if($errorMessage): ?>
        <div class="text-danger form-panel-error"><?php echo $errorMessage; ?></div>
        <?php endif; ?>
        <?php echo $content; ?>
    </div>
</div>