<?php
/** @var \Zend\Form\Element $element */
$element = $this->get('formElement');
$label = ($element->getLabel()) ? $this->formLabel($element) : '';
$markup = $this->formBranchRender($element, 'default', $this->get('mode'));

$labelAttributes = $element->getLabelAttributes();
$labelAttributes['class'] = 'control-label col-sm-4 ' . ((array_key_exists('class', $labelAttributes)) ? $labelAttributes['class'] : '');
$element->setLabelAttributes($labelAttributes);

$classAtt = $element->getAttribute('class');
$classAtt = 'form-control ' . $classAtt;
$element->setAttribute('class', $classAtt);
$type = $element->getAttribute('type');
?>
<div class="form-group collapse wrap-element-row wrap-element-row-<?php echo $type; ?>">
    <?php echo $label; ?>
    <div class="col-sm-8 wrap-element-body"><?php echo $markup; ?></div>
</div>
